version: "2.1"

services:
 timezone:
    build:
  infinitude:
    container_name: infinitude
    hostname: infinitude
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - APP_SECRET=Pogotudinal
      - PASS_REQS=1020
      - MODE=Production
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
